[workspace]
resolver = "2"
members = [
    "crates/sardown-ast",
    "crates/sardown-enrich",
    "crates/sardown-layout",
    "crates/sardown-pdf",
    "crates/sardown-cli",
    "crates/sardown-book",
    "crates/sardown-style",
    "crates/sardown-slides",
]

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/abbra/sardown"
