use cosmic_text::FontSystem;
use sardown_slides::render_slide_deck;
use sardown_style::{SlideLayoutStyle, Stylesheet, VerticalAlign};

fn test_font_system() -> FontSystem {
    let mut db = fontdb::Database::new();
    db.load_font_file(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/DroidSans.ttf")).unwrap();
    db.set_sans_serif_family("Droid Sans");
    FontSystem::new_with_locale_and_db("en-US".to_string(), db)
}

fn small_page_stylesheet() -> Stylesheet {
    let mut sheet = Stylesheet::default();
    sheet.page.width_mm = Some(100.0);
    sheet.page.height_mm = Some(60.0);
    sheet.page.margin_mm = 5.0;
    sheet
}

#[test]
fn a_deck_with_two_thematic_breaks_produces_three_pages() {
    let markdown = "# One\n\n---\n\n# Two\n\n---\n\n# Three\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    assert_eq!(output.pages.len(), 3);
}

#[test]
fn a_layout_directive_selects_the_named_layouts_background() {
    let mut sheet = small_page_stylesheet();
    let title = SlideLayoutStyle { background_color: Some(sardown_style::Color([27, 13, 51])), ..SlideLayoutStyle::default() };
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain Slide\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &sheet).unwrap();

    let has_background =
        |page: &sardown_layout::PositionedPage| matches!(page.elements.first(), Some(sardown_layout::PositionedElement::Path { fill: Some([27, 13, 51]), .. }));
    assert!(has_background(&output.pages[0]), "the title-layout slide should have a background fill");
    assert!(!has_background(&output.pages[1]), "the plain slide should have no background fill");
}

#[test]
fn an_unresolvable_layout_directive_is_a_load_time_error() {
    let markdown = "@layout: nonexistent\n\n# Cover\n";
    let mut fs = test_font_system();
    match render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()) {
        // `{err:#}` (the full chain) rather than plain `{err}` (only the outermost context)
        // since resolve_layout's own message is now wrapped in a per-slide context.
        Err(err) => assert!(format!("{err:#}").contains("nonexistent")),
        Ok(_) => panic!("expected an unresolvable @layout: directive to be a load-time error"),
    }
}

#[test]
fn an_unresolvable_layout_directives_error_names_which_slide_it_was_on() {
    let markdown = "# One\n\n---\n\n@layout: nonexistent\n\n# Two\n";
    let mut fs = test_font_system();
    match render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()) {
        Err(err) => assert!(format!("{err:#}").contains("slide 2"), "expected the error to name slide 2, got: {err:#}"),
        Ok(_) => panic!("expected an unresolvable @layout: directive to be a load-time error"),
    }
}

#[test]
fn a_link_from_one_slide_to_a_heading_on_a_later_slide_resolves_to_the_right_final_page() {
    // Heading ids are auto-generated by slugifying the heading's own text (this project has no
    // `{#id}` attribute syntax) -- "# Target Heading" always slugifies to "target-heading".
    let markdown = "[jump](#target-heading)\n\n---\n\n# Target Heading\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let anchor = output.anchors.get("target-heading").expect("expected the heading's auto-generated slug to be recorded as an anchor");
    assert_eq!(anchor.page, 1, "the heading lives on the second slide (physical page 1)");
}

#[test]
fn header_and_footer_still_render_across_the_whole_concatenated_deck() {
    let mut sheet = small_page_stylesheet();
    sheet.footer.enabled = true;
    sheet.footer.uniform.center = "{page}".to_string();
    let markdown = "# One\n\n---\n\n# Two\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let text_of = |page: &sardown_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                sardown_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
    };
    assert!(text_of(&output.pages[0]).contains(&"1".to_string()));
    assert!(text_of(&output.pages[1]).contains(&"2".to_string()));
}

#[test]
fn a_layout_that_suppresses_the_footer_has_no_footer_on_its_own_slide_only() {
    let mut sheet = small_page_stylesheet();
    sheet.footer.enabled = true;
    sheet.footer.uniform.center = "FOOTER".to_string();
    let title = SlideLayoutStyle { suppress_footer: true, ..SlideLayoutStyle::default() };
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let text_of = |page: &sardown_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                sardown_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
    };
    assert!(!text_of(&output.pages[0]).contains(&"FOOTER".to_string()));
    assert!(text_of(&output.pages[1]).contains(&"FOOTER".to_string()));
}

#[test]
fn vertical_align_center_actually_shifts_content_away_from_the_top_margin() {
    let mut sheet = small_page_stylesheet();
    let title = SlideLayoutStyle { vertical_align: VerticalAlign::Center, ..SlideLayoutStyle::default() };
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\nShort line.\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let margin_pt = sheet.page.margin_mm * 2.834_645_7;
    let first_y = output.pages[0]
        .elements
        .iter()
        .find_map(|e| match e {
            sardown_layout::PositionedElement::TextRun { y, .. } => Some(*y),
            _ => None,
        })
        .expect("expected a text run");
    assert!(first_y > margin_pt + 5.0, "expected centered content to sit well below the top margin ({margin_pt}), got {first_y}");
}

#[test]
fn every_slidelayoutstyle_text_affecting_field_visibly_changes_rendered_output() {
    // Checklist test, not just a regression test: a SlideLayoutStyle field that's meant to change
    // rendered text is wired through one of two independent mechanisms -- build_slide_stylesheet
    // (for fields sardown_layout::layout_impl reads fresh from the Stylesheet at render time) or
    // rescale_slide_content (for fields already baked into each InlineNode's own TextStyle at
    // parse time). Nothing enforces that a new field is wired into whichever mechanism actually
    // owns it -- see Cursor's own doc comment in sardown-layout::paginate for the full split. If
    // you add a text-affecting field to SlideLayoutStyle, add an assertion for it here too, so a
    // silently-no-op wiring mistake fails a test instead of only showing up in a rendered PDF.
    let mut sheet = small_page_stylesheet();
    let layout = SlideLayoutStyle {
        alignment: Some(sardown_style::TextAlignment::Center),
        body_size_pt: Some(30.0),
        text_color: Some(sardown_style::Color([200, 0, 0])),
        secondary_text_color: Some(sardown_style::Color([0, 200, 0])),
        ..SlideLayoutStyle::default()
    };
    sheet.slides.layouts.insert("title".to_string(), layout);
    let markdown = "@layout: title\n\n# Heading\n\nRegular **Bold** text.\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &sheet).unwrap();

    // Every span-run on the same shaped line shares one `text` field (the whole line's text --
    // see shape_rich_paragraph's own doc comment), so runs must be told apart by `size`/`color`,
    // not by substring-matching `text`.
    let text_runs: Vec<(f32, [u8; 3], f32)> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            sardown_layout::PositionedElement::TextRun { size, color, x, .. } => Some((*size, *color, *x)),
            _ => None,
        })
        .collect();

    // alignment: a centered run should not start flush against the left margin.
    let margin_pt = sheet.page.margin_mm * 2.834_645_7;
    assert!(
        text_runs.iter().all(|(_, _, x)| *x > margin_pt + 1.0),
        "expected the layout's centered alignment to shift every run away from the left margin: {text_runs:?}"
    );
    // body_size_pt: the paragraph's own runs should reflect the override (30.0), not typography's
    // own default (12.0) -- headings are deliberately unaffected (their own size table governs
    // them), so paragraph runs are identified by that distinct size.
    let paragraph_runs: Vec<_> = text_runs.iter().filter(|(size, ..)| (*size - 30.0).abs() < 0.01).collect();
    assert!(!paragraph_runs.is_empty(), "expected body_size_pt to produce at least one 30.0pt paragraph run, got {text_runs:?}");
    // text_color: both bold paragraph runs and headings use text_color.
    assert!(paragraph_runs.iter().any(|(_, color, _)| *color == [200, 0, 0]), "expected text_color to color the paragraph's bold run, got {paragraph_runs:?}");
    let heading_run = text_runs.iter().find(|(size, ..)| (*size - 30.0).abs() >= 0.01).expect("expected a heading run at its own distinct size");
    assert_eq!(heading_run.1, [200, 0, 0], "expected text_color to color heading text, got {heading_run:?}");
    // secondary_text_color: non-bold paragraph runs use it instead of text_color.
    assert!(
        paragraph_runs.iter().any(|(_, color, _)| *color == [0, 200, 0]),
        "expected secondary_text_color to color the paragraph's non-bold runs, got {paragraph_runs:?}"
    );
}

#[test]
fn a_layouts_background_image_is_drawn_and_decoded_into_the_final_images_table() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-image.png"),
        corner: sardown_style::ImageCorner::BottomRight,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain Slide\n";
    let mut fs = test_font_system();
    // test-image.png lives in sardown-layout's own fixtures -- reused here rather than duplicated.
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../sardown-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), &base_dir, &mut fs, &sheet).unwrap();

    let has_background_image =
        |page: &sardown_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, sardown_layout::PositionedElement::RasterImage { .. }));
    assert!(has_background_image(&output.pages[0]), "the title-layout slide should have a background image");
    assert!(!has_background_image(&output.pages[1]), "the plain slide should have no background image");
    assert!(output.images.contains_key("test-image.png"), "expected the background image to be decoded into the final images table");
}

#[test]
fn a_layouts_svg_background_image_is_drawn_as_a_vector_graphic() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-vector.svg"),
        corner: sardown_style::ImageCorner::TopLeft,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../sardown-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), &base_dir, &mut fs, &sheet).unwrap();

    let has_background_diagram =
        |page: &sardown_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, sardown_layout::PositionedElement::VectorGraphic { .. }));
    assert!(has_background_diagram(&output.pages[0]), "expected an SVG background image to render as a VectorGraphic");
    assert!(output.diagrams.contains_key("test-vector.svg"), "expected the SVG background image to be compiled into the final diagrams table");
}

#[test]
fn three_slides_sharing_one_layouts_background_image_all_render_it() {
    // Regression coverage for the background-image decode cache in render_slide_deck: decoding
    // is now keyed by path and shared across every slide that uses the same layout, rather than
    // repeated per slide -- this locks in that sharing the cache doesn't break drawing it on
    // every slide that actually needs it.
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-image.png"),
        corner: sardown_style::ImageCorner::BottomRight,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# One\n\n---\n\n@layout: title\n\n# Two\n\n---\n\n@layout: title\n\n# Three\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../sardown-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), &base_dir, &mut fs, &sheet).unwrap();

    let has_background_image =
        |page: &sardown_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, sardown_layout::PositionedElement::RasterImage { .. }));
    for page in &output.pages {
        assert!(has_background_image(page), "every slide sharing the title layout should have its background image drawn");
    }
    assert!(output.images.contains_key("test-image.png"));
}

#[test]
fn a_zero_width_svg_background_image_is_skipped_instead_of_dividing_by_zero() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("zero-width.svg"),
        corner: sardown_style::ImageCorner::TopLeft,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures"));
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), &base_dir, &mut fs, &sheet).unwrap();

    let has_background_diagram =
        |page: &sardown_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, sardown_layout::PositionedElement::VectorGraphic { .. }));
    assert!(!has_background_diagram(&output.pages[0]), "a zero-width source should be skipped, not drawn as a NaN-sized element");
}

#[test]
fn a_layout_can_draw_multiple_background_images_on_the_same_slide() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-image.png"),
        corner: sardown_style::ImageCorner::TopLeft,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    title.background_images.push(sardown_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-vector.svg"),
        corner: sardown_style::ImageCorner::BottomRight,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../sardown-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), &base_dir, &mut fs, &sheet).unwrap();

    let raster_count = output.pages[0].elements.iter().filter(|e| matches!(e, sardown_layout::PositionedElement::RasterImage { .. })).count();
    let vector_count = output.pages[0].elements.iter().filter(|e| matches!(e, sardown_layout::PositionedElement::VectorGraphic { .. })).count();
    assert_eq!(raster_count, 1, "expected exactly one raster background image");
    assert_eq!(vector_count, 1, "expected exactly one vector background image");
}

#[test]
fn a_columns_block_renders_both_columns_side_by_side() {
    let markdown = "::columns\n\n::column\n\n- Left one\n- Left two\n\n::column\n\n- Right one\n\n::end\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let text_of = |page: &sardown_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                sardown_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(" ")
    };
    let full_text = text_of(&output.pages[0]);
    assert!(full_text.contains("Left one") && full_text.contains("Left two"), "expected the left column's own bullets: {full_text}");
    assert!(full_text.contains("Right one"), "expected the right column's own bullet: {full_text}");

    let xs: Vec<f32> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            sardown_layout::PositionedElement::TextRun { x, text, .. } if text.contains("Right one") => Some(*x),
            _ => None,
        })
        .collect();
    let left_xs: Vec<f32> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            sardown_layout::PositionedElement::TextRun { x, text, .. } if text.contains("Left one") => Some(*x),
            _ => None,
        })
        .collect();
    assert!(xs[0] > left_xs[0], "expected the right column's text to start further right than the left column's");
}

#[test]
fn code_blocks_are_syntax_highlighted() {
    // Regression test: render_slide_deck never called the syntax highlighter at all -- every
    // code block rendered in one flat color regardless of language, unlike render/render-book
    // which both call Highlighter::with_style before layout.
    let markdown = "```rust\nfn main() {\n    let x = \"hello\";\n}\n```\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("slides.md"), std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let colors: std::collections::HashSet<[u8; 3]> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            sardown_layout::PositionedElement::TextRun { color, .. } => Some(*color),
            _ => None,
        })
        .collect();
    assert!(colors.len() > 1, "expected multiple distinct token colors from real syntax highlighting, got {colors:?}");
}
