[package]
name = "md2pdf-cli"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "md2pdf"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
cosmic-text = "0.19.0"
fontdb = "0.23"
md2pdf-ast = { path = "../md2pdf-ast" }
md2pdf-enrich = { version = "0.1.0", path = "../md2pdf-enrich" }
md2pdf-layout = { path = "../md2pdf-layout" }
md2pdf-pdf = { version = "0.1.0", path = "../md2pdf-pdf" }

[dev-dependencies]
assert_cmd = "2.2.2"
image = { version = "0.25.10", default-features = false, features = ["png"] }
lopdf = "0.44.0"
pdfium-render = "0.9.3"
proptest = "1.11.0"
