use cosmic_text::FontSystem;
use md2pdf_slides::render_slide_deck;
use md2pdf_style::{SlideLayoutStyle, Stylesheet, VerticalAlign};

fn test_font_system() -> FontSystem {
    let mut db = fontdb::Database::new();
    db.load_font_file(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/DroidSans.ttf")).unwrap();
    db.set_sans_serif_family("Droid Sans");
    FontSystem::new_with_locale_and_db("en-US".to_string(), db)
}

fn small_page_stylesheet() -> Stylesheet {
    let mut sheet = Stylesheet::default();
    sheet.page.width_mm = Some(100.0);
    sheet.page.height_mm = Some(60.0);
    sheet.page.margin_mm = 5.0;
    sheet
}

#[test]
fn a_deck_with_two_thematic_breaks_produces_three_pages() {
    let markdown = "# One\n\n---\n\n# Two\n\n---\n\n# Three\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    assert_eq!(output.pages.len(), 3);
}

#[test]
fn a_layout_directive_selects_the_named_layouts_background() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_color = Some(md2pdf_style::Color([27, 13, 51]));
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain Slide\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &sheet).unwrap();

    let has_background =
        |page: &md2pdf_layout::PositionedPage| matches!(page.elements.first(), Some(md2pdf_layout::PositionedElement::Path { fill: Some([27, 13, 51]), .. }));
    assert!(has_background(&output.pages[0]), "the title-layout slide should have a background fill");
    assert!(!has_background(&output.pages[1]), "the plain slide should have no background fill");
}

#[test]
fn an_unresolvable_layout_directive_is_a_load_time_error() {
    let markdown = "@layout: nonexistent\n\n# Cover\n";
    let mut fs = test_font_system();
    match render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &small_page_stylesheet()) {
        Err(err) => assert!(format!("{err}").contains("nonexistent")),
        Ok(_) => panic!("expected an unresolvable @layout: directive to be a load-time error"),
    }
}

#[test]
fn a_link_from_one_slide_to_a_heading_on_a_later_slide_resolves_to_the_right_final_page() {
    // Heading ids are auto-generated by slugifying the heading's own text (this project has no
    // `{#id}` attribute syntax) -- "# Target Heading" always slugifies to "target-heading".
    let markdown = "[jump](#target-heading)\n\n---\n\n# Target Heading\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let anchor = output.anchors.get("target-heading").expect("expected the heading's auto-generated slug to be recorded as an anchor");
    assert_eq!(anchor.page, 1, "the heading lives on the second slide (physical page 1)");
}

#[test]
fn header_and_footer_still_render_across_the_whole_concatenated_deck() {
    let mut sheet = small_page_stylesheet();
    sheet.footer.enabled = true;
    sheet.footer.uniform.center = "{page}".to_string();
    let markdown = "# One\n\n---\n\n# Two\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let text_of = |page: &md2pdf_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                md2pdf_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
    };
    assert!(text_of(&output.pages[0]).contains(&"1".to_string()));
    assert!(text_of(&output.pages[1]).contains(&"2".to_string()));
}

#[test]
fn a_layout_that_suppresses_the_footer_has_no_footer_on_its_own_slide_only() {
    let mut sheet = small_page_stylesheet();
    sheet.footer.enabled = true;
    sheet.footer.uniform.center = "FOOTER".to_string();
    let mut title = SlideLayoutStyle::default();
    title.suppress_footer = true;
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let text_of = |page: &md2pdf_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                md2pdf_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
    };
    assert!(!text_of(&output.pages[0]).contains(&"FOOTER".to_string()));
    assert!(text_of(&output.pages[1]).contains(&"FOOTER".to_string()));
}

#[test]
fn vertical_align_center_actually_shifts_content_away_from_the_top_margin() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.vertical_align = VerticalAlign::Center;
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\nShort line.\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &sheet).unwrap();
    let margin_pt = sheet.page.margin_mm * 2.834645669;
    let first_y = output.pages[0].elements.iter().find_map(|e| match e {
        md2pdf_layout::PositionedElement::TextRun { y, .. } => Some(*y),
        _ => None,
    }).expect("expected a text run");
    assert!(first_y > margin_pt + 5.0, "expected centered content to sit well below the top margin ({margin_pt}), got {first_y}");
}

#[test]
fn a_layouts_background_image_is_drawn_and_decoded_into_the_final_images_table() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(md2pdf_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-image.png"),
        corner: md2pdf_style::ImageCorner::BottomRight,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n\n---\n\n# Plain Slide\n";
    let mut fs = test_font_system();
    // test-image.png lives in md2pdf-layout's own fixtures -- reused here rather than duplicated.
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../md2pdf-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, &base_dir, &mut fs, &sheet).unwrap();

    let has_background_image =
        |page: &md2pdf_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, md2pdf_layout::PositionedElement::RasterImage { .. }));
    assert!(has_background_image(&output.pages[0]), "the title-layout slide should have a background image");
    assert!(!has_background_image(&output.pages[1]), "the plain slide should have no background image");
    assert!(output.images.contains_key("test-image.png"), "expected the background image to be decoded into the final images table");
}

#[test]
fn a_layouts_svg_background_image_is_drawn_as_a_vector_graphic() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(md2pdf_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-vector.svg"),
        corner: md2pdf_style::ImageCorner::TopLeft,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../md2pdf-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, &base_dir, &mut fs, &sheet).unwrap();

    let has_background_diagram =
        |page: &md2pdf_layout::PositionedPage| page.elements.iter().any(|e| matches!(e, md2pdf_layout::PositionedElement::VectorGraphic { .. }));
    assert!(has_background_diagram(&output.pages[0]), "expected an SVG background image to render as a VectorGraphic");
    assert!(output.diagrams.contains_key("test-vector.svg"), "expected the SVG background image to be compiled into the final diagrams table");
}

#[test]
fn a_layout_can_draw_multiple_background_images_on_the_same_slide() {
    let mut sheet = small_page_stylesheet();
    let mut title = SlideLayoutStyle::default();
    title.background_images.push(md2pdf_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-image.png"),
        corner: md2pdf_style::ImageCorner::TopLeft,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    title.background_images.push(md2pdf_style::BackgroundImageStyle {
        path: std::path::PathBuf::from("test-vector.svg"),
        corner: md2pdf_style::ImageCorner::BottomRight,
        width_pt: 20.0,
        margin_pt: 14.0,
    });
    sheet.slides.layouts.insert("title".to_string(), title);
    let markdown = "@layout: title\n\n# Cover\n";
    let mut fs = test_font_system();
    let base_dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../md2pdf-layout/tests/fixtures"));
    let output = render_slide_deck(markdown, &base_dir, &mut fs, &sheet).unwrap();

    let raster_count = output.pages[0].elements.iter().filter(|e| matches!(e, md2pdf_layout::PositionedElement::RasterImage { .. })).count();
    let vector_count = output.pages[0].elements.iter().filter(|e| matches!(e, md2pdf_layout::PositionedElement::VectorGraphic { .. })).count();
    assert_eq!(raster_count, 1, "expected exactly one raster background image");
    assert_eq!(vector_count, 1, "expected exactly one vector background image");
}

#[test]
fn a_columns_block_renders_both_columns_side_by_side() {
    let markdown = "::columns\n\n::column\n\n- Left one\n- Left two\n\n::column\n\n- Right one\n\n::end\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let text_of = |page: &md2pdf_layout::PositionedPage| {
        page.elements
            .iter()
            .filter_map(|e| match e {
                md2pdf_layout::PositionedElement::TextRun { text, .. } => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(" ")
    };
    let full_text = text_of(&output.pages[0]);
    assert!(full_text.contains("Left one") && full_text.contains("Left two"), "expected the left column's own bullets: {full_text}");
    assert!(full_text.contains("Right one"), "expected the right column's own bullet: {full_text}");

    let xs: Vec<f32> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            md2pdf_layout::PositionedElement::TextRun { x, text, .. } if text.contains("Right one") => Some(*x),
            _ => None,
        })
        .collect();
    let left_xs: Vec<f32> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            md2pdf_layout::PositionedElement::TextRun { x, text, .. } if text.contains("Left one") => Some(*x),
            _ => None,
        })
        .collect();
    assert!(xs[0] > left_xs[0], "expected the right column's text to start further right than the left column's");
}

#[test]
fn code_blocks_are_syntax_highlighted() {
    // Regression test: render_slide_deck never called the syntax highlighter at all -- every
    // code block rendered in one flat color regardless of language, unlike render/render-book
    // which both call Highlighter::with_style before layout.
    let markdown = "```rust\nfn main() {\n    let x = \"hello\";\n}\n```\n";
    let mut fs = test_font_system();
    let output = render_slide_deck(markdown, std::path::Path::new("."), &mut fs, &small_page_stylesheet()).unwrap();
    let colors: std::collections::HashSet<[u8; 3]> = output.pages[0]
        .elements
        .iter()
        .filter_map(|e| match e {
            md2pdf_layout::PositionedElement::TextRun { color, .. } => Some(*color),
            _ => None,
        })
        .collect();
    assert!(colors.len() > 1, "expected multiple distinct token colors from real syntax highlighting, got {colors:?}");
}
