[package]
name = "md2pdf-slides"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
cosmic-text = "0.19.0"
md2pdf-ast = { version = "0.1.0", path = "../md2pdf-ast" }
md2pdf-enrich = { version = "0.1.0", path = "../md2pdf-enrich" }
md2pdf-layout = { version = "0.1.0", path = "../md2pdf-layout" }
md2pdf-style = { version = "0.1.0", path = "../md2pdf-style" }

[dev-dependencies]
fontdb = "0.23"
toml = "1.1.4"
