[package]
name = "md2pdf-layout"
version = "0.1.0"
edition.workspace = true

[dependencies]
cosmic-text = "0.19.0"
fontdb = "0.23"
hyphenation = { version = "0.8", features = ["embed_all"] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
md2pdf-ast = { version = "0.1.0", path = "../md2pdf-ast" }
md2pdf-enrich = { version = "0.1.0", path = "../md2pdf-enrich" }
md2pdf-style = { version = "0.1.0", path = "../md2pdf-style" }
usvg = "0.48.1"
